-- ============================================================================
-- Supabase Schema & Policies: Digit Classification & Active Learning
-- ============================================================================

-- 1. Create Predictions Table (Captures all raw drawing attempts)
CREATE TABLE IF NOT EXISTS public.predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(50) NOT NULL DEFAULT 'sgd',
    predicted_digit INTEGER NOT NULL,
    confidence FLOAT NOT NULL,
    probabilities JSONB NOT NULL,
    image_data JSONB NOT NULL,     -- 784 normalized float pixel array (0.0 - 1.0)
    actual_digit INTEGER,          -- Set by user or admin feedback
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. Create Verified Predictions Table (Curated Ground-Truth Sheet for Retraining)
CREATE TABLE IF NOT EXISTS public.verified_predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediction_id BIGINT UNIQUE,   -- Reference to the original prediction record
    model_name VARCHAR(50) NOT NULL DEFAULT 'sgd',
    predicted_digit INTEGER NOT NULL,
    actual_digit INTEGER NOT NULL, -- Ground-truth human-verified digit (0-9)
    confidence FLOAT NOT NULL,
    probabilities JSONB NOT NULL,
    image_data JSONB NOT NULL,
    verified_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- 3. Row Level Security (RLS)
-- ============================================================================
ALTER TABLE public.predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verified_predictions ENABLE ROW LEVEL SECURITY;

-- Allow anonymous users to insert drawing predictions
CREATE POLICY "Allow public insert to predictions"
ON public.predictions
FOR INSERT
WITH CHECK (true);

-- Allow public read access to predictions (for gallery demo or restricted by role)
CREATE POLICY "Allow public select on predictions"
ON public.predictions
FOR SELECT
USING (true);

-- Allow authenticated users (Admin) to update prediction actual_digit
CREATE POLICY "Allow authenticated update on predictions"
ON public.predictions
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

-- Allow authenticated users (Admin) full access to verified_predictions
CREATE POLICY "Allow authenticated read on verified_predictions"
ON public.verified_predictions
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow authenticated insert/update on verified_predictions"
ON public.verified_predictions
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- ============================================================================
-- 4. Database Trigger Function: Auto-Sync Verified Ground-Truth
-- Whenever a prediction gets an actual_digit label, copy/upsert to verified_predictions
-- ============================================================================
CREATE OR REPLACE FUNCTION public.sync_verified_prediction()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.actual_digit IS NOT NULL THEN
        INSERT INTO public.verified_predictions (
            prediction_id,
            model_name,
            predicted_digit,
            actual_digit,
            confidence,
            probabilities,
            image_data,
            verified_at
        ) VALUES (
            NEW.id,
            NEW.model_name,
            NEW.predicted_digit,
            NEW.actual_digit,
            NEW.confidence,
            NEW.probabilities,
            NEW.image_data,
            now()
        )
        ON CONFLICT (prediction_id) DO UPDATE SET
            actual_digit = EXCLUDED.actual_digit,
            verified_at = now();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger: Execute on Insert or Update of actual_digit in predictions
DROP TRIGGER IF EXISTS trigger_sync_verified_prediction ON public.predictions;
CREATE TRIGGER trigger_sync_verified_prediction
AFTER INSERT OR UPDATE OF actual_digit ON public.predictions
FOR EACH ROW
EXECUTE FUNCTION public.sync_verified_prediction();
